Add --include-root parameter
wp-cli/checksum-command pull request #102
Opened 2023-03-22 02:22 UTC by paulschreiber

## Description
Add `--include-root` parameter. Allows warning for unexpected files in `ABSPATH`.

### Related Issues
Fixes #81.

2023-03-22 05:14 UTC, danielbachhuber requested changes
Thanks for the pull request!

Overall, this is headed in the right direction. Can you add some functional tests covering the change? Here is some [guidance on our pull request best practices](https://make.wordpress.org/cli/handbook/contributions/pull-requests/), if it's helpful.

2023-03-22 13:17 UTC, paulschreiber commented
@danielbachhuber I added a test to `features/checksum-core.feature`. Is that what you wanted? If not, please be more explicit as to the location and nature of tests required.

2023-03-22 13:37 UTC, danielbachhuber reviewed
> I added a test to `features/checksum-core.feature`. Is that what you wanted?

Yep, that's headed in the right direction.

It seems to flag plugins too. Is that expected?

```
$ wp core verify-checksums --include-root
Warning: File should not exist: wp-config.php
Warning: File should not exist: vanilla.wordpress.2023-01-24.000.xml
Warning: File should not exist: update.php
Warning: File should not exist: wp-cli.yml
Warning: File should not exist: white-150-square.jpg
Warning: File should not exist: mysitetitle.wordpress.2022-12-05.004.xml
Warning: File should not exist: vanilla.wordpress.2022-09-11.000.xml
Warning: File should not exist: test.jpg
Warning: File should not exist: mysitetitle.wordpress.2022-12-05.000.xml
Warning: File should not exist: wp-content/plugins/wordpress-importer/parsers/class-wxr-parser-regex.php
Warning: File should not exist: wp-content/plugins/wordpress-importer/parsers/class-wxr-parser.php
Warning: File should not exist: wp-content/plugins/wordpress-importer/parsers/class-wxr-parser-simplexml.php
```

We probably should allow `wp-config.php`.

Also, I didn't debug this, but `wp-cli.yml` is flagged for some reason without the flag included:

```
$ wp core verify-checksums
Warning: File should not exist: wp-cli.yml
Success: WordPress installation verifies against checksums.
```

2023-03-22 14:07 UTC, chesio commented
> What is `wp-cli.yml` used for?

@paulschreiber, see: https://make.wordpress.org/cli/handbook/references/config/#config-files

2023-03-22 14:44 UTC, paulschreiber commented
@chesio Would this file present on production deployments of WordPress?

2023-03-23 03:46 UTC, paulschreiber commented
`wp-cli.yml`is flagged by the existing `^wp-(?!config\.php)([^\/]*)$` regex:
<img width="386" alt="image" src="https://user-images.githubusercontent.com/86784/227097729-26a310d7-d78a-4d56-8d0c-3b68ef52f554.png">

2023-03-23 05:05 UTC, danielbachhuber commented
> `wp-cli.yml`is flagged by the existing `^wp-(?!config\.php)([^\/]*)$` regex:

@paulschreiber Can you expand your tests to cover the expected behavior for `wp-cli.yml`, as well as 31f15fcd753176f4e01ad43d0b22452e2527dd09?

2023-03-23 05:08 UTC, danielbachhuber commented on src/Checksum_Core_Command.php
> +		$this->include_root = false;
Can you initialize `private $include_root = false` on the class itself, to avoid PHP 8 warnings?

2023-03-23 05:08 UTC, danielbachhuber commented on src/Checksum_Core_Command.php
> +	 * : Verify all files in the root directory.
```suggestion
	 * : Verify all files in the root directory, and warn if any non-WordPress files are found.
```

2023-03-23 05:12 UTC, danielbachhuber commented on src/Checksum_Core_Command.php
> +			return ( 1 !== preg_match( '/^(wp-config\.php|wp-content\/plugins)$/', $filepath ) );
I think this needs to exclude all of `wp-content`. It's failing on `mu-plugins`, and will fail on `themes` too:

<img width="1057" alt="image" src="https://user-images.githubusercontent.com/36432/227109200-1f65ea84-21dd-4614-bf58-127e5ca9ed84.png">

In fact, the name `--include-root` implies we're only checking the root directory, so we should probably only check the root directory. We should ignore any subdirectories of root.

2023-03-23 12:44 UTC, paulschreiber commented on src/Checksum_Core_Command.php
> +			return ( 1 !== preg_match( '/^(wp-config\.php|wp-content\/plugins)$/', $filepath ) );
I've updated the regex to exclude `wp-content`.

We don't want to ignore any subdirectories. We want to explicitly check for `ABSPATH/malware/extra.php`

2023-03-23 12:59 UTC, paulschreiber commented
@danielbachhuber I've made changes you requested. I am not sure what tests you wanted for `31f15fc`, but added one for `wp-cli.yml` and added you as a collaborator to the repo.

2023-03-23 14:25 UTC, danielbachhuber reviewed
> I am not sure what tests you wanted for 31f15fc

Specifically, to make sure there are some non-core files in `wp-content` and that it doesn't warn on them. We implicitly should have `akismet` installed, but it would be helpful to include an assertion that: 1) the directory exists, and 2) it's not included in warning output.

2023-03-23 14:25 UTC, danielbachhuber commented on features/checksum-core.feature
> +    When I try `wp core verify-checksums`
```suggestion
    When I run `wp core verify-checksums`
```

We use `When I run` when you expect success, and `When I try` when you expect an error.

2023-03-23 14:25 UTC, danielbachhuber commented on src/Checksum_Core_Command.php
> +			return ( 1 !== preg_match( '/^(wp-config\.php$|wp-content\/)/', $filepath ) );
We should allow `wp-cli.yml` and `wp-cli.local.yml` too.

2023-03-23 14:38 UTC, paulschreiber commented on src/Checksum_Core_Command.php
> +			return ( 1 !== preg_match( '/^(wp-config\.php$|wp-content\/)/', $filepath ) );
1. These files are already disallowed. Is allowing them in scope for this PR?
2. Do you want to allow them only when `--include-root` is passed, only when `--include-root` is not passed, or always?

2023-03-23 14:41 UTC, danielbachhuber commented on src/Checksum_Core_Command.php
> +			return ( 1 !== preg_match( '/^(wp-config\.php$|wp-content\/)/', $filepath ) );
> 1. These files are already disallowed. Is allowing them in scope for this PR?

Ah, if that's the case then we don't need to change the behavior.

2023-03-24 18:12 UTC, danielbachhuber commented
> How do I assert the directory exists? I'm not familiar with this testing framework. Can you make that change?

Yep, I improved upon the tests with d755af78d68c8a64677c3b46d0ffae700ecb7acd

> Also: is there a reason some `Scenario` lines have an extra indent?

I'm not sure why that happened. I removed with 63fd9e7168fff3f322ea7f26f6929a2a6058b430

---

Thanks for your work on this, @paulschreiber ! I'll merge once the tests pass.

2023-03-24 18:37 UTC, danielbachhuber commented
Hm, not quite sure why this failure is happening:

<img width="819" alt="image" src="https://user-images.githubusercontent.com/36432/227611376-9acc9ee6-cd8f-4ae7-8148-a3eccf05dd57.png">

`main` passed just fine a moment ago https://github.com/wp-cli/checksum-command/actions/runs/4513959747

2023-03-24 20:50 UTC, danielbachhuber commented
> Hm, not quite sure why this failure is happening:

Figured it out dc03bc8fa504e3716fffd273072d1fbbb513e5f5

2023-03-24 20:51 UTC, danielbachhuber approved these changes

2023-03-24 20:57 UTC, merged